name: Run API Tests

on:
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          # Crear timestamp y nombre de reporte
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          REPORT_NAME="api_report_${TIMESTAMP}.html"
          echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_ENV
          echo "Reporte generado: $REPORT_NAME"

          pytest --cache-clear --html=$REPORT_NAME --self-contained-html ./api/tests
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_ROLE: ${{ secrets.ADMIN_ROLE }}
          ADMIN_FULL_NAME: ${{ secrets.ADMIN_FULL_NAME }}

      - name: Upload API report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-report-${{ env.TIMESTAMP }}
          path: ${{ env.REPORT_NAME }}
          retention-days: 7
