name: Run UI Tests

on:
  workflow_dispatch:

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest-html

      - name: Run UI tests
        run: |
          pytest -vv --headless --maxfail=1 --disable-warnings \
            --html=ui_report.html --self-contained-html ./UI/tests
        env:
          UI_BASE_URL: ${{ secrets.UI_BASE_URL }}
          UI_SIGNUP_URL: ${{ secrets.UI_SIGNUP_URL }}
          UI_SIGNUP_SUCCESS_URL: ${{ secrets.UI_SIGNUP_SUCCESS_URL }}
          UI_LOGIN_URL: ${{ secrets.UI_LOGIN_URL }}
          UI_LOGIN_SUCCESS_URL: ${{ secrets.UI_LOGIN_SUCCESS_URL }}
          UI_CART_URL: ${{ secrets.UI_CART_URL }}
          UI_MEN_CLOTHES_URL: ${{ secrets.UI_MEN_CLOTHES_URL }}
          UI_WOMEN_CLOTHES_URL: ${{ secrets.UI_WOMEN_CLOTHES_URL }}
          UI_ELECTRONICS_URL: ${{ secrets.UI_ELECTRONICS_URL }}
          UI_BOOKS_URL: ${{ secrets.UI_BOOKS_URL }}
          UI_GROCERIES_URL: ${{ secrets.UI_GROCERIES_URL }}
          UI_SPECIAL_DEALS_URL: ${{ secrets.UI_SPECIAL_DEALS_URL }}
          UI_PRODUCT_URL: ${{ secrets.UI_PRODUCT_URL }}
          UI_CHECKOUT_URL: ${{ secrets.UI_CHECKOUT_URL }}
          UI_CHECKOUT_COMPLETE_URL: ${{ secrets.UI_CHECKOUT_COMPLETE_URL }}

      - name: Upload UI report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: ui_report.html
          retention-days: 7
